<template>
  <CrudMain :config="crudConfig" />
</template>
<script setup>
import CrudMain from "@/econome/components/crud/Main.vue";
import { ref } from "vue";

const crudConfig = ref({
  'tableName': 'dwellers',
  'title': 'Cadastro de Moradores',
  'createButtonText': 'Novo Morador',
  'createModalTitle': 'Adicionar Morador',
  'editModalTitle': 'Editar Morador',
  'viewModalTitle': 'Detalhes do Morador',
  'columns': 2,
  'fields': [
    {
      'title': 'ID',
      'model': 'id',
      'type': 'text',
      'header_styles': '',
      'row_styles': '',
      'column': 1,
      'crudPermissions': {
        'edit': false,
        'create': true,
        'view': true,
        'index': false,
      },
    },
    {
      'title': 'Usuário',
      'model': 'user_id',
      'type': 'number',
      'header_styles': '',
      'row_styles': '',
      'column': 1,
      'crudPermissions': {
        'edit': false,
        'create': true,
        'view': true,
        'index': false,
      },
    },
    {
      'title': 'Nome',
      'model': 'name',
      'type': 'text',
      'header_styles': '',
      'row_styles': 'whitespace-nowrap',
      'required': true,
      'column': 1,
      'crudPermissions': {
        'edit': true,
        'create': true,
        'view': true,
        'index': true,
      },
    },
    {
      'title': 'CPF',
      'model': 'cpf',
      'type': 'text',
      'header_styles': '',
      'row_styles': 'whitespace-nowrap',
      'required': true,
      'column': 1,
      'crudPermissions': {
        'edit': true,
        'create': true,
        'view': true,
        'index': true,
      },
    },
    {
      'title': 'Proprietário',
      'model': 'is_owner',
      'type': 'checkbox',
      'header_styles': 'whitespace-nowrap',
      'row_styles': '',
      'column': 1,
      'crudPermissions': {
        'edit': true,
        'create': true,
        'view': true,
        'index': false,
      },
    },
    {
      'title': 'Celular',
      'model': 'cellphone',
      'type': 'text',
      'header_styles': '',
      'row_styles': 'whitespace-nowrap',
      'required': true,
      'column': 1,
      'crudPermissions': {
        'edit': true,
        'create': true,
        'view': true,
        'index': true,
      },
    },
    {
      'title': 'Data de Nascimento',
      'model': 'birth_date',
      'type': 'date',
      'header_styles': 'whitespace-nowrap',
      'row_styles': 'whitespace-nowrap',
      'required': true,
      'column': 1,
      'crudPermissions': {
        'edit': true,
        'create': true,
        'view': true,
        'index': false,
      },
    },
    {
      'title': 'CEP',
      'model': 'zip_code',
      'type': 'text',
      'header_styles': '',
      'row_styles': 'whitespace-nowrap',
      'required': true,
      'column': 1,
      'crudPermissions': {
        'edit': true,
        'create': true,
        'view': true,
        'index': false,
      },
    },
    {
      'title': 'Rua',
      'model': 'street',
      'type': 'text',
      'header_styles': '',
      'row_styles': 'whitespace-nowrap',
      'required': true,
      'column': 1,
      'crudPermissions': {
        'edit': true,
        'create': true,
        'view': true,
        'index': false,
      },
    },
    {
      'title': 'Número',
      'model': 'number',
      'type': 'text',
      'header_styles': '',
      'row_styles': '',
      'required': true,
      'column': 1,
      'crudPermissions': {
        'edit': true,
        'create': true,
        'view': true,
        'index': false,
      },
    },
    {
      'title': 'Complemento',
      'model': 'complement',
      'type': 'text',
      'header_styles': '',
      'row_styles': '',
      'column': 1,
      'crudPermissions': {
        'edit': true,
        'create': true,
        'view': true,
        'index': false,
      },
    },
    {
      'title': 'Bairro',
      'model': 'neighborhood',
      'type': 'text',
      'header_styles': '',
      'row_styles': 'whitespace-nowrap',
      'required': true,
      'column': 1,
      'crudPermissions': {
        'edit': true,
        'create': true,
        'view': true,
        'index': false,
      },
    },
    {
      'title': 'Cidade',
      'model': 'city',
      'type': 'text',
      'header_styles': '',
      'row_styles': 'whitespace-nowrap',
      'required': true,
      'column': 1,
      'crudPermissions': {
        'edit': true,
        'create': true,
        'view': true,
        'index': false,
      },
    },
    {
      'title': 'Estado',
      'model': 'state',
      'type': 'text',
      'header_styles': '',
      'row_styles': 'whitespace-nowrap',
      'required': true,
      'column': 1,
      'crudPermissions': {
        'edit': true,
        'create': true,
        'view': true,
        'index': false,
      },
    },
    {
      'title': 'Data de Entrada',
      'model': 'entry_date',
      'type': 'date',
      'header_styles': '',
      'row_styles': 'whitespace-nowrap',
      'required': true,
      'column': 2,
      'crudPermissions': {
        'edit': true,
        'create': true,
        'view': true,
        'index': false,
      },
    },
  ],
});
</script>
